name: "SCS BTicino Bridge"
version: "1.0.1"
slug: "scs_bticino"
description: "Integrazione per bus SCS BTicino tramite MQTT"
image: "ghcr.io/home-assistant/{arch}-addon-scs_bticino"
arch:
  - armhf
  - armv7
  - aarch64
startup: application
boot: auto
init: false
host_network: true
privileged:
  - SYS_RAWIO
devices:
  - /dev/ttyAMA0
  - /dev/serial0
ports:
  80/tcp: 8099
  5678/tcp: 5678
options:
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  serial_port: "/dev/serial0"
  debug_mode: false
  log_level: "INFO"
schema:
  mqtt_host: str
  mqtt_port: port
  mqtt_user: str?
  mqtt_password: password?
  serial_port: str
  debug_mode: bool
  log_level: list(DEBUG|INFO|WARNING|ERROR)?