name: "SCS BTicino Bridge"
version: "1.0.9.14"
slug: "scs_bticino"
description: "Integrazione per bus SCS BTicino tramite MQTT"
arch:
  - armhf
  - armv7
  - aarch64
startup: application
boot: auto
init: false
host_network: true
uart: true
gpio: true
full_access: true
apparmor: false

privileged:
  - SYS_RAWIO
  - SYS_ADMIN
  - SYS_RESOURCE

devices:
  - "/dev/serial0:/dev/serial0:rwm"
  - "/dev/ttyAMA0:/dev/ttyAMA0:rwm"
  - "/dev/ttyAMA10:/dev/ttyAMA10:rwm"
  - "/dev/gpiochip0:/dev/gpiochip0:rwm"
  - "/dev/gpiochip1:/dev/gpiochip1:rwm"
  - "/dev/gpiochip2:/dev/gpiochip2:rwm"
  - "/dev/gpiochip3:/dev/gpiochip3:rwm"
  - "/dev/gpiochip4:/dev/gpiochip4:rwm"
  - "/dev/gpiomem:/dev/gpiomem:rwm"
  - "/dev/mem:/dev/mem:rwm"

map:
  - "sys:rw"

options:
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  serial_port: "/dev/serial0"
  debug_mode: false
  log_level: "INFO"
  
schema:
  mqtt_host: str
  mqtt_port: port
  mqtt_user: str?
  mqtt_password: password?
  serial_port: str
  debug_mode: bool
  log_level: list(DEBUG|INFO|WARNING|ERROR)?